### ISSUE TITLE
Server tests aren't running on 2.1.1-rc.1 for todos app

### ISSUE THREAD

**Issue by tmeasday** [practicalmeteor/meteor-mocha#18]
Hey!

I switched the todos app from `avital:mocha`, but now I'm finding the server tests don't run.

You can try it out on the `pm-mocha` branch of the todos app: https://github.com/meteor/todos/tree/pm-mocha

**Comment by jsep** [comment]
For me it's running as expected, I tested with latest meteor release (1.3-rc.4) including unit test and full app tests mode.

Running with unit tests:
![tests](https://cloud.githubusercontent.com/assets/4037939/13927809/9ded6cd6-ef69-11e5-8fa1-e866fa77e1cc.png)

Running full app tests:
![fullapp](https://cloud.githubusercontent.com/assets/4037939/13927839/b97217d6-ef69-11e5-9f2c-e85a7b9c0f01.png)

Note: There are no server tests for full app mode.

**Comment by tmeasday** [comment]
Oh, how odd, now it's working for me. Let's pretend this never happened ;)

**Comment by gadicc** [comment]
@tmeasday could this have been #23?

**Comment by tmeasday** [comment]
@gadicc maaaaybe. Although I don't think I removed mocha-phantomjs..
