### ISSUE TITLE
Height of the client side DOM when testing full-app

### ISSUE THREAD

**Issue by serut** [practicalmeteor/meteor-mocha#21]
When running `meteor test --full-app --driver=practicalmeteor:mocha`, your client side DOM is inside a block with 0px height.

That means that the jquery selector `:visible` is not usable anymore.
```
    chai.expect($('#foo:visible')[0]).to.not.be.undefined; // always undefined
```

Is it possible to fix this behavior ?

**Comment by rbabayoff** [comment]
@serut this is the behavior of --full-app by design, this is a meteor issue, I suggest consulting @tmeasday about how meteor and us can support those types of tests. @tmeasday?

**Comment by tmeasday** [comment]
Yeah, it's a limitation of the `--full-app` test approach. My advice would be either:
1. Don't use visibility checks, instead just existence checks for DOM related stuff.
2. If you want to write tests that care about appearance based things, it's probably best to write an [acceptance test](http://guide.meteor.com/testing.html#acceptance-testing)

**Comment by serut** [comment]
Ok I didn't thought it was desired. 

I close the issue since it's not even the good repository ! ;-)
