### ISSUE TITLE
Arguments not checked

### ISSUE THREAD

**Issue by XavaDigital** [practicalmeteor/meteor-mocha#22]
I'm running the test runner having just installed it and not written any tests yet. I have audit-argument-checks installed.

I'm seeing a couple of errors.

- Exception from sub mochaServerRunEvents id 5WAnND4B9E582sSPz Error: Did not check() all arguments during publisher 'mochaServerRunEvents'
- Exception while invoking method 'mocha/runServerTests' Error: Did not check() all arguments during call to 'mocha/runServerTests'

The test runner works fine when I remove audit-argument-checks from the project. Do I have to remove audit-argument-checks for testing? is there a simple way to do this for testing only?

**Comment by rbabayoff** [comment]
@XavaDigital / @vangorra do all meteor packages with publish functions that don't check input arguments create the same problem when being added to an app with audit-argument-checks?

**Comment by vangorra** [comment]
Yes, all meteor packages with publish/method functions that don't check input arguments create the same problem when being added to an app with audit-argument-checks.

I noticed you were using chai to perform those checks. Certainly a robust solution. Sadly however, calling check() will be necessary to avoid issues when projects use the audit-arguments-checks package.

On a related note:
It would be rather easy to create a check-chai package that exposes chai as a means to perform the check() calls.

**Comment by rbabayoff** [comment]
Got it @vangorra, will merge your pr shortly. And yes, it would, I really prefer chai's bdd syntax and the fact it has some amazing plugins, such as the sinon one we use extensively in our tests. Let's see if you or I ever get around to creating check-chai :-)
