### ISSUE TITLE
Change --save option to --save-dev in warning message

### ISSUE THREAD

**Issue by nhducit** [practicalmeteor/meteor-mocha#24]
In #19 issue's description, we should change **--save** to **--save-dev** because these are test dependencies.

warning from issue #19 
```
Consider running: meteor npm install **--save** browser growl jade sass stylus less
markdown discount markdown-js marked coffee-script
```

warning from my machine:

```
Consider running: meteor npm install **--save** browser growl jade mocha
```

**Comment by rbabayoff** [comment]
@nhducit this is a warning message generated by meteor, not by us. Don't know if meteor supports --save-dev / devDependencies in 1.3. We need to check. Meteor should specify to --save-dev if those warning messages originate from code packages that are testOnly. @tmeasday / @benjamn?

**Comment by tmeasday** [comment]
I think this would make sense if it's easy @benjamn?

**Comment by benjamn** [comment]
If you `meteor update` to 1.3.1, I believe these warnings will no longer appear at all, as we've disabled them for packages, pending a better solution like https://github.com/meteor/meteor/issues/6322.

**Comment by rbabayoff** [comment]
Closing this, since it's a meteor issue and since warning messages are not displayed in meteor 1.3.1.
