### ISSUE TITLE
Errors thrown in hooks aren't reported when testing packages

### ISSUE THREAD

**Issue by quintstoffers** [practicalmeteor/meteor-mocha#27]
Repro repo: https://github.com/quintstoffers/pm-mocha-hook-repro

An error in a `before` or `beforeEach` hook is registered as a failure, but the failing hook + stack trace is never shown in the reporter. It's manageable when running a small number of tests, but as projects grow bigger it gets more and more difficult to find the broken hook.

Oddly enough running the exact same test in `test` mode instead of `test-packages` does behave correctly.

**Comment by jsep** [comment]
Thanks @quintstoffers  this will be fixed in the next release of the package

**Comment by quintstoffers** [comment]
Perfect, thanks!

**Comment by jsep** [comment]
@quintstoffers you can try the `2.4.5-rc.3` version it should fix this issue

**Comment by quintstoffers** [comment]
Looks like 2.4.5-rc.3 works fine, thanks! The console runner seems to be left behind a bit, although that's another issue all together.
