### ISSUE TITLE
mocha.css will be ignored as UTF-8 is the only encoding supported

### ISSUE THREAD

**Issue by ManuelDeLeon** [practicalmeteor/meteor-mocha#9]
I'm getting the following ~~error~~ warning when I run the tests:

`packages/practicalmeteor_mocha/mocha.css: warn: @charset rules in this file will be ignored as UTF-8 is the only encoding supported`

**Comment by rbabayoff** [comment]
Its not an error, its a warning that won't fail your tests I beleive (please confirm), but we'll take a look at how to remove that warning.
